version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'users_microservice'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'postgres'
    ports:
      - "5433:5432"
    volumes:
      - my-db:/var/lib/postgres/data
    networks:
      deploy_net:
  backend-users:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_IP=host.docker.internal
      - DB_PORT=5432
      - DB_DBNAME=users_microservice
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - APPLICATION_SECRET=DAGQYQG78ERFG78FWEBUISDFJBKZSFDU
    networks:
      deploy_net:
        ipv4_address: 172.30.11.2

volumes:
  my-db:

networks:
  deploy_net:
    external: true
